import { FormEvent, useState } from "react";
import { Building2, LockKeyhole, ShieldCheck, UserRound } from "lucide-react";
import { useAuth } from "../context/AuthContext";
const API = import.meta.env.VITE_API_URL ?? "http://127.0.0.1:8000";

export default function Login() {
  const { login } = useAuth(); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch(`${API}/api/auth/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail ?? "Authentication failed."); login(data.access_token, data.user); } catch (err) { setError(err instanceof Error ? err.message : "Authentication failed."); } finally { setLoading(false); } };
  return <main className="relative flex min-h-screen items-center justify-center overflow-hidden bg-slate-50 px-4"><div className="login-grid absolute inset-0 opacity-40" /><div className="absolute -left-32 top-1/4 h-96 w-96 rounded-full bg-indigo-200/40 blur-3xl" /><div className="absolute -right-32 bottom-1/4 h-96 w-96 rounded-full bg-blue-100/70 blur-3xl" /><section className="relative w-full max-w-md rounded-3xl border border-slate-200/80 bg-white p-8 shadow-executive"><div className="mb-8 text-center"><div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-indigo-600 text-white shadow-lg shadow-indigo-600/20"><Building2 size={29} /></div><p className="eyebrow text-indigo-600">Secure administrative gateway</p><h1 className="mt-2 text-2xl font-black tracking-tight text-slate-900">INUKA UNIFIED PORTAL</h1><p className="mt-2 text-sm text-slate-500">Beneficiary security and access management.</p></div>{error && <div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</div>}<form onSubmit={submit} className="space-y-5"><label className="label">Account username<div className="relative mt-2"><UserRound className="absolute left-3 top-3 text-slate-400" size={16} /><input required autoComplete="username" className="field pl-10" placeholder="admin_kamau" value={username} onChange={(event) => setUsername(event.target.value)} /></div></label><label className="label">System key password<div className="relative mt-2"><LockKeyhole className="absolute left-3 top-3 text-slate-400" size={16} /><input required type="password" autoComplete="current-password" className="field pl-10" placeholder="Enter your password" value={password} onChange={(event) => setPassword(event.target.value)} /></div></label><button className="action-primary w-full justify-center py-3" disabled={loading}>{loading ? "Establishing security tunnel..." : "Secure access login"}</button></form><div className="mt-7 flex items-center justify-center gap-2 border-t border-slate-100 pt-4 text-[10px] font-bold uppercase tracking-wider text-slate-400"><ShieldCheck size={14} className="text-emerald-500" /> AES-256 system encryption active</div></section></main>;
}
